/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_CognitivTrainingControl_t {
  public final static EE_CognitivTrainingControl_t COG_NONE = new EE_CognitivTrainingControl_t("COG_NONE", edkJNI.COG_NONE_get());
  public final static EE_CognitivTrainingControl_t COG_START = new EE_CognitivTrainingControl_t("COG_START");
  public final static EE_CognitivTrainingControl_t COG_ACCEPT = new EE_CognitivTrainingControl_t("COG_ACCEPT");
  public final static EE_CognitivTrainingControl_t COG_REJECT = new EE_CognitivTrainingControl_t("COG_REJECT");
  public final static EE_CognitivTrainingControl_t COG_ERASE = new EE_CognitivTrainingControl_t("COG_ERASE");
  public final static EE_CognitivTrainingControl_t COG_RESET = new EE_CognitivTrainingControl_t("COG_RESET");

  public final int swigValue() {
    return swigValue;
  }

  @Override
  public String toString() {
    return swigName;
  }

  public static EE_CognitivTrainingControl_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_CognitivTrainingControl_t.class + " with value " + swigValue);
  }

  private EE_CognitivTrainingControl_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_CognitivTrainingControl_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_CognitivTrainingControl_t(String swigName, EE_CognitivTrainingControl_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_CognitivTrainingControl_t[] swigValues = { COG_NONE, COG_START, COG_ACCEPT, COG_REJECT, COG_ERASE, COG_RESET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

