/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_CognitivEvent_t {
  public final static EE_CognitivEvent_t EE_CognitivNoEvent = new EE_CognitivEvent_t("EE_CognitivNoEvent", edkJNI.EE_CognitivNoEvent_get());
  public final static EE_CognitivEvent_t EE_CognitivTrainingStarted = new EE_CognitivEvent_t("EE_CognitivTrainingStarted");
  public final static EE_CognitivEvent_t EE_CognitivTrainingSucceeded = new EE_CognitivEvent_t("EE_CognitivTrainingSucceeded");
  public final static EE_CognitivEvent_t EE_CognitivTrainingFailed = new EE_CognitivEvent_t("EE_CognitivTrainingFailed");
  public final static EE_CognitivEvent_t EE_CognitivTrainingCompleted = new EE_CognitivEvent_t("EE_CognitivTrainingCompleted");
  public final static EE_CognitivEvent_t EE_CognitivTrainingDataErased = new EE_CognitivEvent_t("EE_CognitivTrainingDataErased");
  public final static EE_CognitivEvent_t EE_CognitivTrainingRejected = new EE_CognitivEvent_t("EE_CognitivTrainingRejected");
  public final static EE_CognitivEvent_t EE_CognitivTrainingReset = new EE_CognitivEvent_t("EE_CognitivTrainingReset");
  public final static EE_CognitivEvent_t EE_CognitivAutoSamplingNeutralCompleted = new EE_CognitivEvent_t("EE_CognitivAutoSamplingNeutralCompleted");
  public final static EE_CognitivEvent_t EE_CognitivSignatureUpdated = new EE_CognitivEvent_t("EE_CognitivSignatureUpdated");

  public final int swigValue() {
    return swigValue;
  }
  
  @Override
  public String toString() {
    return swigName;
  }

  public static EE_CognitivEvent_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_CognitivEvent_t.class + " with value " + swigValue);
  }

  private EE_CognitivEvent_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_CognitivEvent_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_CognitivEvent_t(String swigName, EE_CognitivEvent_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_CognitivEvent_t[] swigValues = { EE_CognitivNoEvent, EE_CognitivTrainingStarted, EE_CognitivTrainingSucceeded, EE_CognitivTrainingFailed, EE_CognitivTrainingCompleted, EE_CognitivTrainingDataErased, EE_CognitivTrainingRejected, EE_CognitivTrainingReset, EE_CognitivAutoSamplingNeutralCompleted, EE_CognitivSignatureUpdated };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

