/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_DataChannel_t {
  public final static EE_DataChannel_t ED_COUNTER = new EE_DataChannel_t("ED_COUNTER", edkJNI.ED_COUNTER_get());
  public final static EE_DataChannel_t ED_INTERPOLATED = new EE_DataChannel_t("ED_INTERPOLATED");
  public final static EE_DataChannel_t ED_RAW_CQ = new EE_DataChannel_t("ED_RAW_CQ");
  public final static EE_DataChannel_t ED_AF3 = new EE_DataChannel_t("ED_AF3");
  public final static EE_DataChannel_t ED_F7 = new EE_DataChannel_t("ED_F7");
  public final static EE_DataChannel_t ED_F3 = new EE_DataChannel_t("ED_F3");
  public final static EE_DataChannel_t ED_FC5 = new EE_DataChannel_t("ED_FC5");
  public final static EE_DataChannel_t ED_T7 = new EE_DataChannel_t("ED_T7");
  public final static EE_DataChannel_t ED_P7 = new EE_DataChannel_t("ED_P7");
  public final static EE_DataChannel_t ED_O1 = new EE_DataChannel_t("ED_O1");
  public final static EE_DataChannel_t ED_O2 = new EE_DataChannel_t("ED_O2");
  public final static EE_DataChannel_t ED_P8 = new EE_DataChannel_t("ED_P8");
  public final static EE_DataChannel_t ED_T8 = new EE_DataChannel_t("ED_T8");
  public final static EE_DataChannel_t ED_FC6 = new EE_DataChannel_t("ED_FC6");
  public final static EE_DataChannel_t ED_F4 = new EE_DataChannel_t("ED_F4");
  public final static EE_DataChannel_t ED_F8 = new EE_DataChannel_t("ED_F8");
  public final static EE_DataChannel_t ED_AF4 = new EE_DataChannel_t("ED_AF4");
  public final static EE_DataChannel_t ED_GYROX = new EE_DataChannel_t("ED_GYROX");
  public final static EE_DataChannel_t ED_GYROY = new EE_DataChannel_t("ED_GYROY");
  public final static EE_DataChannel_t ED_TIMESTAMP = new EE_DataChannel_t("ED_TIMESTAMP");
  public final static EE_DataChannel_t ED_ES_TIMESTAMP = new EE_DataChannel_t("ED_ES_TIMESTAMP");
  public final static EE_DataChannel_t ED_FUNC_ID = new EE_DataChannel_t("ED_FUNC_ID");
  public final static EE_DataChannel_t ED_FUNC_VALUE = new EE_DataChannel_t("ED_FUNC_VALUE");
  public final static EE_DataChannel_t ED_MARKER = new EE_DataChannel_t("ED_MARKER");
  public final static EE_DataChannel_t ED_SYNC_SIGNAL = new EE_DataChannel_t("ED_SYNC_SIGNAL");

  public final int swigValue() {
    return swigValue;
  }

  @Override
  public String toString() {
    return swigName;
  }

  public static EE_DataChannel_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_DataChannel_t.class + " with value " + swigValue);
  }

  private EE_DataChannel_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_DataChannel_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_DataChannel_t(String swigName, EE_DataChannel_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_DataChannel_t[] swigValues = { ED_COUNTER, ED_INTERPOLATED, ED_RAW_CQ, ED_AF3, ED_F7, ED_F3, ED_FC5, ED_T7, ED_P7, ED_O1, ED_O2, ED_P8, ED_T8, ED_FC6, ED_F4, ED_F8, ED_AF4, ED_GYROX, ED_GYROY, ED_TIMESTAMP, ED_ES_TIMESTAMP, ED_FUNC_ID, ED_FUNC_VALUE, ED_MARKER, ED_SYNC_SIGNAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

