/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_ExpressivTrainingControl_t {
  public final static EE_ExpressivTrainingControl_t EXP_NONE = new EE_ExpressivTrainingControl_t("EXP_NONE", edkJNI.EXP_NONE_get());
  public final static EE_ExpressivTrainingControl_t EXP_START = new EE_ExpressivTrainingControl_t("EXP_START");
  public final static EE_ExpressivTrainingControl_t EXP_ACCEPT = new EE_ExpressivTrainingControl_t("EXP_ACCEPT");
  public final static EE_ExpressivTrainingControl_t EXP_REJECT = new EE_ExpressivTrainingControl_t("EXP_REJECT");
  public final static EE_ExpressivTrainingControl_t EXP_ERASE = new EE_ExpressivTrainingControl_t("EXP_ERASE");
  public final static EE_ExpressivTrainingControl_t EXP_RESET = new EE_ExpressivTrainingControl_t("EXP_RESET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EE_ExpressivTrainingControl_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_ExpressivTrainingControl_t.class + " with value " + swigValue);
  }

  private EE_ExpressivTrainingControl_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_ExpressivTrainingControl_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_ExpressivTrainingControl_t(String swigName, EE_ExpressivTrainingControl_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_ExpressivTrainingControl_t[] swigValues = { EXP_NONE, EXP_START, EXP_ACCEPT, EXP_REJECT, EXP_ERASE, EXP_RESET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

