/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_ExpressivEvent_t {
  public final static EE_ExpressivEvent_t EE_ExpressivNoEvent = new EE_ExpressivEvent_t("EE_ExpressivNoEvent", edkJNI.EE_ExpressivNoEvent_get());
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingStarted = new EE_ExpressivEvent_t("EE_ExpressivTrainingStarted");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingSucceeded = new EE_ExpressivEvent_t("EE_ExpressivTrainingSucceeded");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingFailed = new EE_ExpressivEvent_t("EE_ExpressivTrainingFailed");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingCompleted = new EE_ExpressivEvent_t("EE_ExpressivTrainingCompleted");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingDataErased = new EE_ExpressivEvent_t("EE_ExpressivTrainingDataErased");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingRejected = new EE_ExpressivEvent_t("EE_ExpressivTrainingRejected");
  public final static EE_ExpressivEvent_t EE_ExpressivTrainingReset = new EE_ExpressivEvent_t("EE_ExpressivTrainingReset");

  public final int swigValue() {
    return swigValue;
  }

  @Override
  public String toString() {
    return swigName;
  }

  public static EE_ExpressivEvent_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_ExpressivEvent_t.class + " with value " + swigValue);
  }

  private EE_ExpressivEvent_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_ExpressivEvent_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_ExpressivEvent_t(String swigName, EE_ExpressivEvent_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_ExpressivEvent_t[] swigValues = { EE_ExpressivNoEvent, EE_ExpressivTrainingStarted, EE_ExpressivTrainingSucceeded, EE_ExpressivTrainingFailed, EE_ExpressivTrainingCompleted, EE_ExpressivTrainingDataErased, EE_ExpressivTrainingRejected, EE_ExpressivTrainingReset };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

