/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public final class EE_ExpressivSignature_t {
  public final static EE_ExpressivSignature_t EXP_SIG_UNIVERSAL = new EE_ExpressivSignature_t("EXP_SIG_UNIVERSAL", edkJNI.EXP_SIG_UNIVERSAL_get());
  public final static EE_ExpressivSignature_t EXP_SIG_TRAINED = new EE_ExpressivSignature_t("EXP_SIG_TRAINED");

  public final int swigValue() {
    return this.swigValue;
  }

  @Override
  public String toString() {
    return this.swigName;
  }

  public static EE_ExpressivSignature_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EE_ExpressivSignature_t.class + " with value " + swigValue);
  }

  private EE_ExpressivSignature_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EE_ExpressivSignature_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EE_ExpressivSignature_t(String swigName, EE_ExpressivSignature_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EE_ExpressivSignature_t[] swigValues = { EXP_SIG_UNIVERSAL, EXP_SIG_TRAINED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

