/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public class InputSensorDescriptor_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected InputSensorDescriptor_t(long cPtr, boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  protected static long getCPtr(InputSensorDescriptor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        edkJNI.delete_InputSensorDescriptor_t(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  public void setChannelId(SWIGTYPE_p_EE_InputChannels_t value) {
    edkJNI.InputSensorDescriptor_t_channelId_set(this.swigCPtr, this, SWIGTYPE_p_EE_InputChannels_t.getCPtr(value));
  }

  public SWIGTYPE_p_EE_InputChannels_t getChannelId() {
    return new SWIGTYPE_p_EE_InputChannels_t(edkJNI.InputSensorDescriptor_t_channelId_get(this.swigCPtr, this), true);
  }

  public void setFExists(int value) {
    edkJNI.InputSensorDescriptor_t_fExists_set(this.swigCPtr, this, value);
  }

  public int getFExists() {
    return edkJNI.InputSensorDescriptor_t_fExists_get(this.swigCPtr, this);
  }

  public void setPszLabel(String value) {
    edkJNI.InputSensorDescriptor_t_pszLabel_set(this.swigCPtr, this, value);
  }

  public String getPszLabel() {
    return edkJNI.InputSensorDescriptor_t_pszLabel_get(this.swigCPtr, this);
  }

  public void setXLoc(double value) {
    edkJNI.InputSensorDescriptor_t_xLoc_set(this.swigCPtr, this, value);
  }

  public double getXLoc() {
    return edkJNI.InputSensorDescriptor_t_xLoc_get(this.swigCPtr, this);
  }

  public void setYLoc(double value) {
    edkJNI.InputSensorDescriptor_t_yLoc_set(this.swigCPtr, this, value);
  }

  public double getYLoc() {
    return edkJNI.InputSensorDescriptor_t_yLoc_get(this.swigCPtr, this);
  }

  public void setZLoc(double value) {
    edkJNI.InputSensorDescriptor_t_zLoc_set(this.swigCPtr, this, value);
  }

  public double getZLoc() {
    return edkJNI.InputSensorDescriptor_t_zLoc_get(this.swigCPtr, this);
  }

  public InputSensorDescriptor_t() {
    this(edkJNI.new_InputSensorDescriptor_t(), true);
  }

}
