/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dfki.km.text20.trackingserver.brain.adapter.impl.emotiv.raw.v1.wrapper;

public class SWIGTYPE_p_EmoStateHandle {
  private long swigCPtr;

  protected SWIGTYPE_p_EmoStateHandle(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_EmoStateHandle() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_EmoStateHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

